# Generated by Django 2.0.6 on 2018-07-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mouse", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="record", name="user_agent"),
        migrations.AddField(
            model_name="record",
            name="is_bot",
            field=models.BooleanField(default=False, help_text="If user is a bot."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="is_email_client",
            field=models.BooleanField(
                default=False, help_text="If user is an email client."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="is_mobile",
            field=models.BooleanField(default=False, help_text="If user is mobile."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="is_pc",
            field=models.BooleanField(default=False, help_text="If user is pc."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="is_tablet",
            field=models.BooleanField(default=False, help_text="If user is tablet."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="is_touch_capable",
            field=models.BooleanField(
                default=False, help_text="If user is touch capable."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="ua_string",
            field=models.TextField(default=False, help_text="User agent description."),
            preserve_default=False,
        ),
    ]
